### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: Qwen/Qwen3-1.7B
adapter_name_or_path: /projects/p32344/Reasoning/AIME2023/saves/dpo_aime/lora
template: qwen3
trust_remote_code: true

### export
export_dir: /projects/p32344/Reasoning/AIME2023/saves/dpo_aime/merged
export_size: 5
export_device: cpu
export_legacy_format: false
